### ISSUE TITLE
 Kata Levels List and Learning Move(Items)

### ISSUE THREAD

**Issue by tokidoki11** [gokatas/gokatas#1]
Im trying to get my feet to golang

would appreciate if
1. There is levels of the kata (maybe easy, medium, hard)
2. or, set of moves(items) to be learned in the kata

Thanks

**Comment by jreisinger** [comment]
Hello @tokidoki11 and thanks for your input. I've actually considered both your points and this is my view:

1. The level of a kata is represented by its size, i.e. the number of lines - the 1st column in the `gokatas` output (`go install github.com/gokatas/gokatas@latest && gokatas`). The level in the form easy/medium/hard is more difficult to define because it very much depends on the background of the student (for example pointers are quite difficult for some but of no concern for C programmers).
2. I first put something like moves in the topics of each repo and displayed them as "Topics" column in the `gokatas` output. But later I changed them to standard library packages because they are easy to define and they still describe the moves in a sense (e.g. if you see the `net` package you know it's about networking - try `go doc net`). Also the kata description (e.g. "io.Writer implementation", or "concurrency patterns") and the documentation inside the katas (`go doc`) provide useful information.

**Comment by tokidoki11** [comment]
@jreisinger 
Well understood!

Thanks for the library!
